/*! modify-docs.js */

module.exports = function(grunt) {
  grunt.registerMultiTask('modifyDocs', 'Modifying documents', function() {
    var options = this.options();
    var count = 0;
    this.files.forEach(function(file) {
      file.src.forEach(function(src) {
        modifyDocs(grunt, src, options);
        count++;
      });
    });
    grunt.log.writeln(count + ' files modified');
  });
};

function modifyDocs(grunt, file, options) {
  // grunt.log.writeln(file);
  var html = grunt.file.read(file);
  html = html.split(/\n/).map(function(line) {
    if (line.search(/Documentation generated by.*<\/a> on/) > -1) {
      line = line.replace(/<\/a> on[^<]+/, '</a>');
    }
    return line;
  }).join('\n');
  grunt.file.write(file, html);
}
